# .streamlit/secrets.toml
[azure]
cosmos_endpoint = "https://cogorisk-insights-db.documents.azure.com:443/"
cosmos_key = "aeJzT920sDjuQx1TU3UdlOhiCIgvjBEhNmp6HeVIW7FEvuZQdmM2UEmz4nglZJC9f9v0Hsk60437ACDbG50Keg=="
storage_connection_string = "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=cogosensordata;AccountKey=K0SlE8vHLBdGZq0GUHFXBDAjBUkSJrCRguMp5OK22N0eKA7YUyP0uv03IjQJOvmafTzdM4cYj6Mc+AStZ6XnFw=="

[openai]
api_key = "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"
